### ISSUE TITLE
LICENSE or permission to reuse code?

### ISSUE THREAD

**Issue by sparr** [m4thpro/m4thpro.github.io#1]
Would you be willing to add a LICENSE file to your repo, or to specifically here give me permission to modify and redistribute some of your code in my pico8 library repo https://github.com/sparr/pico8lib ?

**Comment by bartsnapp** [comment]
Hi,

I've added the MIT license to my stuff

**Comment by kisonecat** [comment]
I've also added a LICENSE file to mine, so I think we've got all the repos covered now.

Thank you for pointing this out.
